### ISSUE TITLE
S-1 TOPS Split function - Unexpected Exception

### ISSUE THREAD

**Issue by steekhutzie** [senbox-org/snap-desktop#13]
Launching function from menu 'Radar->Sentinel-1 TOPS->S-1 TOPS Split' everything works as expected on Windows 10.

Working on Ubuntu 14.04 from GUI, SNAP vers. 3.0, S1TBX vers 3.0.1 same function gives UnexpectedException with the following details.

```
java.lang.NullPointerException
    at javax.swing.plaf.basic.BasicSliderUI.recalculateIfInsetsChanged(BasicSliderUI.java:946)
    at javax.swing.plaf.basic.BasicSliderUI.getPreferredSize(BasicSliderUI.java:469)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
    at java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1115)
    at java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:916)
    at java.awt.GridBagLayout.preferredLayoutSize(GridBagLayout.java:736)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:96)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:492)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:96)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:492)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2304)
    at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.preferredLayoutSize(BasicTabbedPaneUI.java:2278)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
    at java.awt.Container.preferredSize(Container.java:1796)
    at java.awt.Container.getPreferredSize(Container.java:1780)
    at java.awt.Window.pack(Window.java:809)
    at org.esa.snap.ui.AbstractDialog.show(AbstractDialog.java:236)
    at org.esa.snap.graphbuilder.rcp.dialogs.SingleOperatorDialog.show(SingleOperatorDialog.java:154)
    at org.esa.snap.graphbuilder.rcp.actions.OperatorAction.actionPerformed(OperatorAction.java:64)
    at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
    at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
    at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
    at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
    at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by lveci** [comment]
Yes, it seems related to the look and feel used.
http://forum.step.esa.int/t/bug-topsar-split-function-missing-in-version-3-0/1884/9

**Comment by steekhutzie** [comment]
I'm using Gnome and I do not have Metal neither Nimbus themes available. However, I tried all of the available themes (Ambiance, Radiance, Highcontrast) and SNAP raises always the same exception as reported above.

**Comment by lveci** [comment]
Thanks for the information. The safest thing to do would be not to use the JIDE slider and just stick to Java swing slider. Although now we may need two controls instead of one that does both.
