### ISSUE TITLE
SNAP error after any command in linux

### ISSUE THREAD

**Issue by jmigueldelgado** [senbox-org/snap-desktop#43]
I am getting an error when performing any kind of command in SNAP. To illustrate the error I am running a dummy classification on a GRD-type scene. I am running a linux machine with ubuntu xenial 16.04 LTS.

The dummy process I am running is a K-Means Cluster Analysis with the following parameters:

`<parameters>
    <clusterCount>2</clusterCount>
    <iterationCount>10</iterationCount>
    <randomSeed>31415</randomSeed>
    <roiMaskName/>
</parameters>`

The error is always the same:

> A java.lang.NullPointerException exception has occurred.

When I click show details I get the following:

> java.lang.NullPointerException
> 	at org.esa.snap.core.gpf.Operator.ensureSingleRasterSize(Operator.java:555)
> 	at org.esa.snap.cluster.KMeansClusterOp.initialize(KMeansClusterOp.java:93)
> 	at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:486)
> 	at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:273)
> 	at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:387)
> 	at org.esa.snap.core.gpf.GPF.createProductNS(GPF.java:318)
> 	at org.esa.snap.core.gpf.GPF.createProduct(GPF.java:293)
> 	at org.esa.snap.core.gpf.GPF.createProduct(GPF.java:272)
> 	at org.esa.snap.core.gpf.ui.DefaultSingleTargetProductDialog.createTargetProduct(DefaultSingleTargetProductDialog.java:137)
> [catch] at org.esa.snap.core.gpf.ui.SingleTargetProductDialog.onApply(SingleTargetProductDialog.java:131)
> 	at org.esa.snap.ui.AbstractDialog.lambda$initUI$6(AbstractDialog.java:523)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jmigueldelgado** [comment]
Be sure to open the correct file (the *.zip file) before you start asking silly questions in github....
