### ISSUE TITLE
SNAP desktop version 6.0：“Copy pixel-info to clipboard”function no response  

### ISSUE THREAD

**Issue by bloodbaby** [senbox-org/snap-desktop#48]
OS：Win10 Pro 64
already tried to paste in notebook，old clipboard info still unchanged

**Comment by marpet** [comment]
From which product are you copying the pixel information?
Is it processed, if so, how? Is it stored on disk?
If you try to get the pixel-info from a processed product which is not yet written to disk, the data needs to be processed first. Depending on the processing graph this might take a while.

**Comment by bloodbaby** [comment]
@marpet 
- product ID：S1A_IW_GRDH_1SDV_20171205T100355_20171205T100420_019566_02139E_923B

- processed procedures： 
    1. unzip the product 
    2. open product in SNAP 6.0 using mainfest.safe file in product folder 
    3. show a real band of amplitude_VH 
    4. select a single pixel and right click 

Also need to mention : 
    1. open SNAP in administrator mode
    2. tried more than 10 times, wait for more than 30 seconds still nothing happened, even the 
        buffering icon didn't show, usually the processing stage you mentioned finish in 10 seconds

**Comment by marpet** [comment]
I tried to reproduce this and got this error:
```
java.lang.OutOfMemoryError: Java heap space
	at org.esa.snap.core.datamodel.TiePointGrid.ensureMinLengthArray(TiePointGrid.java:951)
	at org.esa.snap.core.datamodel.TiePointGrid.getPixels(TiePointGrid.java:584)
	at org.esa.snap.core.datamodel.TiePointGrid.getPixels(TiePointGrid.java:638)
	at org.esa.snap.core.datamodel.TiePointGrid.getRasterData(TiePointGrid.java:401)
	at org.esa.snap.core.datamodel.RasterDataNode.hasRasterData(RasterDataNode.java:913)
	at org.esa.snap.core.datamodel.Product.createPixelInfoString(Product.java:2042)
	at org.esa.snap.rcp.actions.tools.CopyPixelInfoToClipboardAction.copyPixelInfoStringToClipboard(CopyPixelInfoToClipboardAction.java:104)
	at org.esa.snap.rcp.actions.tools.CopyPixelInfoToClipboardAction.actionPerformed(CopyPixelInfoToClipboardAction.java:81)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI.doClick(VsnetMenuItemUI.java:1395)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI$MouseInputHandler.mouseReleased(VsnetMenuItemUI.java:1190)
	at java.awt.Component.processMouseEvent(Unknown Source)
```
Actually I should have enough memory, But something is strange with the tie-points here.
Will further investigate.

**Comment by marpet** [comment]
The tie-points load to much data into memory. I've added a ticket in our issue tracker: [SNAP-889](https://senbox.atlassian.net/browse/SNAP-889)

As workaround you can create a subset of the data:
1) use context menu of the view and select 'Create Spatial Subset from View'. Should be small enough.
2) open an image view from the subset 
3) select the pixel you want the information for
